@startuml
actor User
participant Server
participant UserController
participant UserModel
participant UserService
database Postgresql

User --> Server: validate reset form (newPassword, token)
Server --> UserController: ResetPassword(new password, token)
UserController --> UserModel: CheckResetToken()
note over UserModel
  Checks the request
  params contains a
  valid reset token
end note
UserController <-- UserModel: OK
UserController --> UserModel: SetPassword(new password)
UserController <-- UserModel
UserController --> UserService: Save(user)
UserService --> Postgresql: UPDATE user
UserService <-- Postgresql
UserController <-- UserService
UserController --> UserService: DeleteResetLink(reset link)
UserService --> Postgresql: DELETE reset link
UserService <-- Postgresql
UserController <-- UserService


Server <-- UserController
User <-- Server

@enduml
