@startuml
actor User
participant Server
participant UserController
participant UserModel

User --> Server: click reset link
Server --> UserController: ResetForm()
UserController --> UserModel: CheckResetToken()
note over UserModel
  Checks the URL contains
  a valid reset token
end note
UserController <-- UserModel: OK

Server <-- UserController: Reset Form
User <-- Server: Reset Form
note over User
  the reset form includes
  the reset token in hidden
  params
end note
@enduml
