@startuml
actor User
participant Server
participant UserController
participant auth
participant UserService
participant SmtpServer
database Postgresql

User --> Server: POST SendResetLink(email)
Server --> UserController: SendResetLink(email)
UserController --> auth: GetResetToken(email)
UserController <-- auth: reset token
note right
  the reset link contains
  a JWT token with a validity
  duration of 5 minutes only
end note
UserController --> UserService: Save(reset token)
UserService --> Postgresql: save reset token in user profile
note right
  expired reset link
  should/could be
  deleted when login
end note
UserService <-- Postgresql
UserController <-- UserService
UserController --> UserService: SendResetLink(reset token)
UserService --> SmtpServer: SendMail(reset link)
UserController <-- UserService
Server <-- UserController
User <-- Server
@enduml
