- hosts: dev
  connection: local
  
  vars:
     tmp_directory: "{{ playbook_dir }}/deploy"

  roles:
    - role: package
 

- hosts: production
  
  remote_user: root
  
  vars:
     tmp_directory: "{{ playbook_dir }}/deploy"
  
  roles:
    - role: supervisor
    - role: deploy