##########  App checkout and build ##########

# - name: Delete the previous build
#   file: >
#     path="{{ tmp_directory }}"
#     state=absent

- name: Get Git executable path
  command: which git
  register: result

- name: Get stuff from git
  local_action: >
    git repo=git@bitbucket.org:plemerrer/bleuvanille.git
    dest="{{ tmp_directory }}"
    update=yes
    version={{ reference }}
    force=yes
    executable="{{ result.stdout }}"

- name: Prepare the static assets (JS, CSS, images, fonts...)
  command: >
    chdir="{{ tmp_directory }}"
    gulp dist

- name: Download dependencies
  environment: { 'GOPATH':'{{ tmp_directory }}' }
  command: >
    chdir="{{ tmp_directory }}/src/bleuvanille"
    glide install --update-vendored

- name: Fix link to step definitions
  file: >
    src='{{ tmp_directory }}/../node_modules/bitter-apple/bitter-apple-gherkin.js'
    path='{{ tmp_directory }}/features/step_definitions/bitter-apple-gherkin.js'
    state=link

- name: Build the Go application for tests
  environment: { 'GOPATH':'{{ tmp_directory }}' }
  command: >
    chdir="{{ tmp_directory }}"
    go build src/bleuvanille/server.go
