##########  Supervisor installation and configuration ##########

- name: Install supervisor when required
  apt: >
    name=supervisor
    state=latest
  tags: ['supervisor']

- name: Create logs directory
  file: >
    state=directory
    path="{{ logs_dir }}"
  tags: ['supervisor']

- name: Copy the supervisord config
  copy: >
    src=supervisord.conf
    dest="{{ supervisor_config_dir }}"
  tags: ['supervisor', 'deploy']

- name: Reload supervisor configuration
  command: supervisorctl reload
  tags: ['supervisor', 'deploy']
