# - name: Create arangodb configuration file
#   template: >
#     src=arangodb.j2
#     dest=/home/pascal/arangodb/arangodb.conf
#   notify: restart arangodb
#   tags: ['setup', 'deploy', 'arangodb']

- name: create arangodb user group
  group: name=arangodb gid=999 state=present
  tags: ['setup', 'deploy', 'arangodb']

- name: create arangodb user
  user: name=arangodb uid=999 group=arangodb
  tags: ['setup', 'deploy', 'arangodb']

- name: create arangoDB data directory
  file: path=/home/pascal/arangodb/data state=directory owner=arangodb group=arangodb mode=0700
  tags: ['setup', 'deploy', 'arangodb']

# - name: create arangoDB log directory
#   file: path=/home/pascal/arangodb/logs state=directory owner=pascal group=pascal mode=0700
#   tags: ['setup', 'deploy', 'arangodb']

# - name: create arangoDB JS directory
#   file: path=/home/pascal/arangodb/js state=directory owner=pascal group=pascal mode=0700
#   tags: ['setup', 'deploy', 'arangodb']

- name: create arangoDB extension directory
  file: path=/home/pascal/arangodb/apps state=directory owner=arangodb group=arangodb mode=0700
  tags: ['setup', 'deploy', 'arangodb']

# - name: copy empty JS application required by arangoDB to start???
#   copy: >
#     src=app.js
#     dest="/home/pascal/arangodb/js/app.js"
#   tags: ['setup', 'deploy', 'arangodb']

# - name: install apt-transport-https
#   apt: pkg='apt-transport-https' state='present'
#   tags: ['setup', 'deploy', 'arangodb']

# - name: update apt repository
#   apt: update_cache=yes cache_valid_time=3600
#   tags: ['setup', 'deploy', 'arangodb']

# - name: install arangodb
#   apt: name='arangodb=2.8.9' state='present'
#   register: installed
#   tags: ['setup', 'deploy', 'arangodb']

# - name: enable arangodb
#   service: name='arangodb' enabled=yes
#   tags: ['setup', 'deploy', 'arangodb']

# - name: stop arangodb
#   service: name='arangodb' state='stopped'
#   when: installed.changed and arangodb_autoupgrade is defined and arangodb_autoupgrade
#   tags: arangodb

# - name: run arangodb upgrade
#   shell: '/etc/init.d/arangodb upgrade'
#   when: installed.changed and arangodb_autoupgrade is defined and arangodb_autoupgrade
#   tags: arangodb

# - name: start arangodb
#   service: name='arangodb' state='started'
#   when: installed.changed and arangodb_autoupgrade is defined and arangodb_autoupgrade
#   tags: arangodb